language: python

python:
  - 2.7
  - 3.6

env:
  - NET_SNMP_VERSION=5.7.3

before_install:
  # Install build dependencies
  - sudo apt-get update
  - sudo apt-get install -y autoconf libtool make libperl-dev python-dev
  - sudo apt-get install -y snmp snmpd snmp-mibs-downloader

  # Start up SNMPD with our test config
  - snmpd -C -c tests/snmpd.conf

  # Ensure that all mibs are loaded by the SNMP client/client library
  # SNMP will prefer $HOME/.snmp/snmp.conf over /usr/local/etc/snmp.conf
  - mkdir -m 0755 ~/.snmp
  - echo 'mibs +ALL' > ~/.snmp/snmp.conf

install:
  # Install the build requirements
  - pip install -r dev-requirements.txt
  - pip install coveralls

script:
  # Run the unit tests using py.test
  - python setup.py test

after_script:
  # Stop the SNMPD daemon
  - pkill snmpd

after_success:
  # Send coverage statistics to Coveralls
  coveralls

notifications:
  # Disable email notifications if something fails
  email: false
