language: python
python:
- 2.7
env:
- NET_SNMP_VERSION=5.7.3
before_install:
- sudo apt-get update
- sudo apt-get install -y autoconf libtool make libperl-dev python-dev
- sudo apt-get install -y snmp snmpd snmp-mibs-downloader
- snmpd -C -c tests/snmpd.conf
- snmpget -v 2c -c public localhost:11161 1.3.6.1.2.1.1.1.0
- which snmpset
- mkdir -m 0755 ~/.snmp
- echo 'mibs +ALL' > ~/.snmp/snmp.conf
install:
- pip install --upgrade pip setuptools tox termcolor virtualenv coveralls
script:
- tox -v
after_script:
- pkill snmpd
after_success: coveralls
notifications:
  email: false
deploy:
  provider: pypi
  user: "netauto"
  password:
    secure: kIDRhXD2f4y9aGoHIHxSUUY/uSKCB8hVNhrM5GG6zGjJw/zmCV2QLc52rP8WslsUDeW9QWPeo3IQXm+NZwj0PQ/Hz0lt9Kw6w1u9viZwIpLqbpnpt4Y+eOiowpbZidk5bknNcjo0rcsNFRuRQZFooPxS8KxuAiiMdKens8ZOEvzLC4rXFSChUjpQcbBYCdbDMEWXHDvSDXvqr5SfT7j1yRPBEIPKUAZRldNg22nq/7uCedlwsRFtHgiZayJHt2WVMsE8WSSDJ6QXrBah5+rS9sr9Gt3cRZEcBK6GTekJ/SqpKLGxjTwGVXBtUrxPoBrYBoYBriCOVN8ayOWipoOXw0mqcDQ9nt6Kf3x42NV1eBsz4MnvBtNyUV+KLqx7jGcInGxjX9W+STx/zem8/DQYVOv/T5Qa9DhUtwAdvxE0Ezc+WRInt2yzMEIoO4mpx/fyhPkbNca8xrCWWGZbcECEt3gxEN3PDCUixyCM2txksB6bqMrHAwt1L3/WSFAsc8izyAcLrp6IdX8mvtWF3kSBf2FGAsETO8W3I7vSb+SjVIiECCh74sVSM3PLBdzGXvBz3r02TMJfqzzG+ED2lIJ6lg1tQkgNCHlpq/HmKWCIraStVRjp9VHJj6LZ47pUyGz+eFCDm+lhhD7lzwvmRcBm0jVmtusZkTFqi4LKxJTllDw=
  distributions: "sdist"
